blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="home"),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.homeview, name="home"),
    
]

pwebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('core.urls')),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
	created_by = models.ForeignKey(User)
	post_title = models.CharField(max_length=250)
	brief = models.CharField(max_length=5000)
	body = models.TextField()
	created_on = models.DateTimeField(default=datetime.now)

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk':self.pk})

	def __str__(self):
		return self.post_title

class Like(models.Model):
	user = models.ForeignKey(User, related_name='liked_by')
	post = models.ForeignKey(Post)
	created = models.DateTimeField(default = datetime.now)

core/models.py
from django.db import models
# Create your models here.

class HomeSkills(models.Model):
	name = models.CharField(max_length=1000)

	class Meta:
		verbose_name = "Home Skill"
		verbose_name_plural = "Home Skills"
	def __str__(self):
		return self.name

class ContactDetails(models.Model):
	name = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	website = models.CharField(max_length=100)
	phone = models.CharField(max_length=100)
	mobile = models.CharField(max_length=100)
	address = models.TextField()

	def __str__(self):
		return self.name

class MiscText(models.Model):
	about_text = models.TextField()
	profile_text = models.TextField()
	skill_text = models.TextField()
	certification_text = models.TextField()
	contact_text = models.TextField()
	resume_url = models.CharField(max_length=1000)
	profilepic_url = models.CharField(max_length=1000)


class Social(models.Model):
	name = models.CharField(max_length=100)
	url = models.CharField(max_length=1000)

	class Meta: 
		verbose_name = "Social"
		verbose_name_plural = "Social"

	def __str__(self):
		return self.name

class Skill(models.Model):
	name = models.CharField(max_length=100)
	proficiency = models.IntegerField()
	order = models.PositiveIntegerField(default=1, null =False, blank = False)

	def __str__(self):
		return self.name

class Certification(models.Model):
	name = models.CharField(max_length=1000)
	provider = models.CharField(max_length=1000)
	url = models.CharField(max_length=1000)
	order = models.PositiveIntegerField(default=1, null =False, blank = False)

	class Meta:
		verbose_name= "Certification"
		verbose_name_plural = "Certifications"

	def __str__(self):
		return self.name

class Profile(models.Model):
	profile_topic = models.CharField(max_length=100)
	value = models.CharField(max_length=1000)
	order = models.PositiveIntegerField()

	def __str__(self):
		return self.profile_topic

class WorkExperience(models.Model):
	position = models.CharField(max_length=100)
	organization = models.CharField(max_length=1000)
	start_date = models.CharField(max_length=100)
	end_date = models.CharField(max_length=100)
	description = models.TextField()
	certificate = models.CharField(max_length=10000, verbose_name="Certificate Link (google drive)")
	order = models.PositiveIntegerField()


	class Meta:
		verbose_name = "Work Experience"
		verbose_name_plural = "Work Experiences"

	def __str__(self):
		return self.organization

class Academic(models.Model):
	institution = models.CharField(max_length=1000)
	degree = models.CharField(max_length=1000)
	start_date = models.CharField(max_length=100)
	end_date = models.CharField(max_length=100)
	description = models.TextField()
	marksheet = models.CharField(max_length=1000)
	order = models.PositiveIntegerField()

	class Meta:
		verbose_name = "Academic"

	def __str__(self):
		return self.institution

class Quote(models.Model):
	text = models.TextField()
	citiation = models.CharField(max_length=100)

	def __str__(self):
		return self.text

class Project(models.Model):
	name = models.CharField(max_length=1000)
	github_url = models.CharField(max_length=1000)
	url = models.CharField(max_length=1000)
	tech = models.CharField(max_length=10000, verbose_name="Technology Stack Used")
	description = models.TextField()
	image_url = models.CharField(max_length=10000)

	def __str__(self):
		return self.name

blog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.views.generic import View

from .models import *

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'blog/home.html'
	context_object_name = 'all_posts'

	def get_queryset(self):
		return Post.objects.order_by('-created_on')[:40]

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post.html'

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from core.models import *
from blog.models import *
# Create your views here.


def homeview(request):
	home_skills = HomeSkills.objects.all()
	social = Social.objects.all()
	certification = Certification.objects.order_by('order')[:6]
	skills = Skill.objects.order_by('order')[:6]
	academics = Academic.objects.order_by('-order')
	work = WorkExperience.objects.order_by('-order')
	profile = Profile.objects.order_by('order')
	quotes = Quote.objects.all()
	projects = Project.objects.all()
	contact = ContactDetails.objects.all()
	post = Post.objects.order_by('-created_on')[:5]
	misctext = MiscText.objects.all()

	context = {
		'home_skills': home_skills,
		'social' : social,
		'certification': certification,
		'skills' : skills,
		'work' : work,
		'academics': academics,
		'profile' : profile,
		'quotes' : quotes,
		'projects' : projects,
		'contact' : contact,
		'posts': post,
		'misctext': misctext
	}
	print('social')
	return render(request, "home/home.html", context)

blog/templates/blog/home.html
	{% extends 'home/base.html' %}
	
	{% block title %}Blog{% endblock %}

	{% block extrastyles %}
		<style>
			.author{
				font-size: 0.5em;
			}
			footer{
				padding-top: 3rem;
			}
			hr{
				width: 73%;
			}
		</style>
	{% endblock %}

	{% block content %}

	<header>   	
   	<div class="row">

   		<div class="top-bar">
   			<a class="menu-toggle" href="#"><span>Menu</span></a>	      

		   	<nav id="main-nav-wrap">
					<ul class="main-navigation">
						<li class="current"><a href="{% url 'core:home' %}" title="">Home</a></li>
						<li><a class="smoothscroll"  href="#blog" title="">Posts</a></li>				
					</ul>
				</nav>    		
   		</div> <!-- /top-bar --> 
   		
   	</div> <!-- /row --> 		
   </header> <!-- /header -->

	<!-- intro section
   ================================================== -->
   <section id="intro">   

   	<div class="intro-overlay"></div>	

   	<div class="intro-content">
   		<div class="row">

   			<div class="col-twelve">

	   			<h5>print('Hello, World')</h5>
	   			<h1>Hey! I'm Sahadev Bite</h1>

	   			<p class="intro-position">
	   				<span>This is my personal blogging platform</span>
	   			</p>

	   			<a class="button stroke smoothscroll" href="#blog" title="">Read Posts</a>

	   		</div>  
   			
   		</div>   		 		
   	</div> <!-- /intro-content -->     	

   </section> <!-- /intro -->

	   <!-- posts section
   ================================================== -->
   <section id="blog">  

   	<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>Posts</h5>
   			
   		</div>   		
   	</div> <!-- /section-intro -->
		{% for post in all_posts %}

   		<div class="row">
				<div class="col-twelve">
					<h1 class="title" style="padding-top: 3rem;"><a href="{{ post.id }}">{{ post.post_title }}</a><p class="author">by {{ post.created_by }}</p></h1>
					<p class = "metadata">{{ post.created_on }} | 3 likes</p>
					<p class="body">{{ post.brief }}</p>
				</div>
		</div>
		<hr>


		{% endfor  %}

   	<div class="row button-section">
   		<div class="col-twelve">
   			<a href="#" title="< Previous" class="button">< Previous</a>
   			<a href="#" title="Next >" class="button button-primary">Next ></a>
   		</div>   		
   	</div>

   </section>
 
 	{% endblock %}

blog/templates/blog/post.html
	{% extends 'home/base.html' %}
	
	{% block title %}{{ post.post_title }}{% endblock %}

	{% block extrastyles %}
		<style>
			.author{
				font-size: 0.5em;
			}
			#intro{
				    height: 50%;
		    min-height: 500px;
			}
			#blog{
				padding-top: 0;
			}
			footer{
				padding-top: 3rem;
			}
		</style>
	{% endblock %}

	{% block content %}

	<header>   	
   	<div class="row">

   		<div class="top-bar">
   			<a class="menu-toggle" href="#"><span>Menu</span></a>	      

		   	<nav id="main-nav-wrap">
					<ul class="main-navigation">
						<li class="current"><a href="{% url 'core:home' %}" title="">Home</a></li>
						<li><a href="{% url 'blog:home' %}" title="">Blog</a></li>				
					</ul>
				</nav>    		
   		</div> <!-- /top-bar --> 
   		
   	</div> <!-- /row --> 		
   </header> <!-- /header -->

	<!-- intro section
   ================================================== -->
   <section id="intro">   

   	<div class="intro-overlay"></div>	

   	<div class="intro-content">
   		<div class="row">

   			<div class="col-twelve">

<!-- 	   			<h5>print('Hello, World')</h5> -->
	   			<h1>{{ post.post_title }}</h1>

	   			<p class="intro-position">
	   				<span>Posted by {{post.created_by}} on {{post.created_on}}</span>
	   			</p>

	   			<!-- <a class="button stroke smoothscroll" href="#blog" title="">Read Posts</a> -->

	   		</div>  
   			
   		</div>   		 		
   	</div> <!-- /intro-content -->     	

   </section> <!-- /intro -->

	   <!-- posts section
   ================================================== -->
   <section id="blog">  

   		<div class="row">
				<div class="col-twelve" style="text-align: center">
					<h1 class="title" style="padding-top: 3rem;">{{ post.post_title }}<p class="author">by Sahadev bite</p></h1>
					<p class = "metadata">{{post.created_on}} | 3 likes</p>
					<p class="body">{{post.body | safe}}</p>

					<a class="button" href="#"><i class="fa fa-thumbs-up"></i>Like</a>
				</div>
		</div>
   </section>
   

  {% endblock %}

core/templates/home/base.html
<!DOCTYPE html>
<!--[if IE 8 ]><html class="no-js oldie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js oldie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="no-js" lang="en"> <!--<![endif]-->
<head>

   <!--- basic page needs
   ================================================== -->
   <meta charset="utf-8">
	<title>{% block title %}Home{% endblock %} | Sahadev Bite</title>
	<meta name="description" content="personal website of Sahadev Bite">  
	<meta name="author" content="Sahadev Uttam Bite, Sahadev, Sahadev Bite">

   <!-- mobile specific metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

 	<!-- CSS
   ================================================== -->
   {% load static %}
   <link rel="stylesheet" href="{% static 'home/css/base.css' %}">
   <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
   <link rel="stylesheet" href="{% static 'home/css/vendor.css' %}">    

   <link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">

   {% block extrastyles %}{% endblock %}

   <!-- script
   ================================================== -->   
	<script src="{% static 'home/js/modernizr.js' %}"></script>
	<script src="{% static 'home/js/pace.min.js' %}"></script>
	{% block extrascripts %}{% endblock %}

   <!-- favicons
	================================================== -->
  <link rel="shortcut icon" type="image/png" href="{% static 'home/favicon.ico' %}"/>

</head>

<body id="top">

	{% block content %}
	{% endblock %}


   <!-- footer
   ================================================== -->

   <footer>
     	<div class="row">

     		<div class="col-six tab-full pull-right social">

     			<ul class="footer-social">        
            {% for list in social %}
               <li><a href="{{ list.url }}"><i class="fa fa-{{ list.name }}"></i></a></li>
            {% endfor %}
			   </ul> 
	      		
	      </div>

      	<div class="col-six tab-full">
	      	<div class="copyright">
		        	<span>© Copyright sahadev.me 2017</span> 
		        	<span>Source available at <a href="www.github.com/rajujha373"><i class="fa fa-github"></i></a></span>	         	
		         </div>		                  
	      	</div>

	      	<div id="go-top">
		         <a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-long-arrow-up"></i></a>
		      </div>

      	</div> <!-- /row -->     	
   </footer>  

   <div id="preloader"> 
    	<div id="loader"></div>
   </div> 

   <!-- Java Script
   ================================================== --> 
   <script src="{% static 'home/js/jquery-2.1.3.min.js' %}"></script>
   <script src="{% static 'home/js/plugins.js' %}"></script>
   <script src="{% static 'home/js/main.js' %}"></script>
   <script src="{% static 'home/js/particle.js' %}"></script>
   <script src="{% static 'home/js/app.js' %}"></script>

</body>

</html>

core/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}

		<!-- header 
		   ================================================== -->
		   {% include 'home/includes/header.html' %}

			<!-- intro section
		   ================================================== -->
			{% include 'home/includes/intro.html' %}


		   <!-- about section
		   ================================================== -->
		    {% include 'home/includes/about.html' %}


		   <!-- resume Section
		   ================================================== -->
			{% include 'home/includes/resume.html' %}


			<!-- Portfolio Section
		   ================================================== -->
			{% include 'home/includes/projects.html' %}


			
			<!-- Quote Section
		   ================================================== -->
			{% include 'home/includes/quotes.html' %}


			<!-- Projects Section 
			================================================= -->
			{% include 'home/includes/blog.html' %}


		   <!-- contact
		   ================================================== -->
			{% include 'home/includes/contact.html' %}

{% endblock %}

core/templates/home/includes/about.html
   {% load static %}
   <section id="about">  
   
   	<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>About</h5>
   			<h1>Hey Guys!</h1>

   			<div class="intro-info">
               {% for text in misctext %}
      				<img src="{{text.profilepic_url}}" alt="Profile Picture">
               {% endfor %}
               {% for text in misctext %}
      				<p class="lead">{{ text.about_text | safe }}</p>
               {% endfor %}
   			</div>   			

   		</div>   		
   	</div> <!-- /section-intro -->

   	<div class="row about-content">

   		<div class="col-four tab-full">

   			<h3>Profile</h3>
               {% for text in misctext %}
         			<p>{{ text.profile_text }}</p>
               {% endfor %}
   			<ul class="info-list">
            {% for list in profile %}
   				<li>
   					<strong>{{list.profile_topic}}</strong>
   					<span>{{list.value}}</span>
   				</li>
            {% endfor %}

   			</ul> <!-- /info-list -->

   		</div>

   		<div class="col-four tab-full">

   			<h3>Skills</h3>
   			{% for text in misctext %}
                  <p>{{ text.skill_text }}</p>
               {% endfor %}

				<ul class="skill-bars">
               {% for skill in skills %}
   				   <li>
   				   	<div class="progress percent{{ skill.proficiency }}"><span>{{skill.proficiency}}%</span></div>
   				   	<strong>{{ skill.name }}</strong>
   				   </li>
               {% endfor %}
      
				</ul> <!-- /skill-bars -->		

   		</div>

   		<div class="col-four tab-full">

   			<h3>Certifications</h3>
      			{% for text in misctext %}
                  <p>{{ text.certification_text }}</p>
               {% endfor %}

				<ul class="info-list">
            {% for list in certification %}
   				<li>
   					<strong>{{list.name}}</strong>
   					<span><a href="{{list.url}}" title="View Certificate">{{list.provider}}</a></span>
   				</li>
            {% endfor %}

   			</ul> <!-- /info-list -->	

   		</div>

   	</div>

   	<div class="row button-section">
   		<div class="col-twelve">
   			<a href="#contact" title="Hire Me" class="button stroke smoothscroll">Hire Me</a>
            {% for text in misctext %}
      			<a href="{{ text.resume_url }}" title="Download CV" class="button button-primary">Download CV</a>
   		   {% endfor %}
         </div>   		
   	</div>

   </section> <!-- /process-->

core/templates/home/includes/academic.html
<div class="row resume-timeline">

   		<div class="col-twelve resume-header">

   			<h2>Education</h2>

   		</div> <!-- /resume-header -->

   		<div class="col-twelve">

   			<div class="timeline-wrap">
			{% for academic in academics %}
	   			<div class="timeline-block">

	   				<div class="timeline-ico">
	   					<i class="fa fa-graduation-cap"></i>
	   				</div>

	   				<div class="timeline-header">
	   					<h3>{{ academic.degree }}</h3>
	   					<p>{{academic.start_date }} - {{academic.end_date}} </p>
	   				</div>

	   				<div class="timeline-content">
	   					<h4>{{academic.institution}} <a href="{{work.certificate}}" title="View Marksheet"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></h4>
	   					<p>{{academic.description}}</p>
	   				</div>

	   			</div> <!-- /timeline-block -->
	   		{% endfor %}

   			</div> <!-- /timeline-wrap -->   			

   		</div> <!-- /col-twelve -->
   		
   	</div> <!-- /resume-timeline -->

core/templates/home/includes/blog.html
{% load static %}

<section id="blog">

		<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>Blog</h5>
   			<h1>Check Out My Articles.</h1>

   		</div>   		
   	</div> <!-- /section-intro--> 
	<div class="row">
	<div id="blog-carousal" class="owl-carousel">
		{% for post in posts %}
			<div class="post-list">
				<div class="row">
					<div class="col-twelve">
						<h1 class="title"><a href="blog/{{post.id}}">{{post.post_title}}</a><p class="author">by {{post.created_by}}</p></h1>
						<p class = "metadata">{{post.created_on}} | 3 likes</p>
						<p class="body">{{post.brief}}</p>
					</div>
				</div>
			</div>
		{% endfor %}

	</div>
		<div class="row section-intro">
   		<div class="col-twelve">

			<p><a href="{% url 'blog:home' %}">See All Posts</a></p>

   		</div>   		
   	</div> <!-- /section-intro-->
	</div>

	</section> <!-- /poss --> 

core/templates/home/includes/contact.html
<section id="contact">

		<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>Contact</h5>
   			<h1>I'd Love To Hear From You.</h1>
            {% for text in misctext %}
      			<p class="lead">{{ text.contact_text }}</p>
            {% endfor %}

   		</div> 
   	</div> <!-- /section-intro -->

   	     <div class="row contact-form">

         <div class="col-twelve">


            <!-- form -->
            <form name="contactForm" id="contactForm" method="post" action="">
               <fieldset>

                  <div class="form-field">
                     <input name="contactName" type="text" id="contactName" placeholder="Name" value="" minlength="2" required="">
                  </div>
                  <div class="form-field">
                     <input name="contactEmail" type="email" id="contactEmail" placeholder="Email" value="" required="">
                  </div>
                  <div class="form-field">
                     <input name="contactSubject" type="text" id="contactSubject" placeholder="Subject" value="">
                  </div>                       
                  <div class="form-field">
                     <textarea name="contactMessage" id="contactMessage" placeholder="message" rows="10" cols="50" required=""></textarea>
                  </div>                      
                 <div class="form-field">
                     <button class="submitform">Submit</button>
                     <div id="submit-loader">
                        <div class="text-loader">Sending...</div>                             
                        <div class="s-loader">
                           <div class="bounce1"></div>
                           <div class="bounce2"></div>
                           <div class="bounce3"></div>
                        </div>
                     </div>
                  </div>

               </fieldset>
            </form> <!-- Form End -->

            <!-- contact-warning -->
            <div id="message-warning">             
            </div>            
            <!-- contact-success -->
            <div id="message-success">
               <i class="fa fa-check"></i>Your message was sent, thank you!<br>
            </div>

         </div> <!-- /col-twelve -->
         
      </div> <!-- /contact-form -->


      {% for contact in contact %}
   	<div class="row contact-info">

   		<div class="col-four tab-full">

   			<div class="icon">
   				<i class="icon-pin"></i>
   			</div>

   			<h5>Where to find me</h5>

   			<p>{{contact.address | safe }}</p>

   		</div>

   		<div class="col-four tab-full collapse">

   			<div class="icon">
   				<i class="icon-mail"></i>
   			</div>

   			<h5>Get Me Online At</h5>

   			<p>{{contact.email}}<br>
			   	{{contact.website}}			     
			   </p>

   		</div>

   		<div class="col-four tab-full">

   			<div class="icon">
   				<i class="icon-phone"></i>
   			</div>

   			<h5>Call Me At</h5>

   			<p>Mobile: {{contact.phone}}<br>
			     	Alternative: {{contact.mobile}}
			   </p>

   		</div>
   		
   	</div> <!-- /contact-info -->
      {% endfor %}
		
	</section> <!-- /contact -->

core/templates/home/includes/header.html
<header>   	
   	<div class="row">

   		<div class="top-bar">
   			<a class="menu-toggle" href="#"><span>Menu</span></a>	      

		   	<nav id="main-nav-wrap">
					<ul class="main-navigation">
						<li class="current"><a class="smoothscroll"  href="#intro" title="">Home</a></li>
						<li><a class="smoothscroll"  href="#about" title="">About</a></li>
						<li><a class="smoothscroll"  href="#resume" title="">Work & Education</a></li>
						<li><a class="smoothscroll"  href="#portfolio" title="">Projects</a></li>
						<li><a class="smoothscroll"  href="#blog" title="">Blog</a></li>					
						<li><a class="smoothscroll"  href="#contact" title="">Contact</a></li>				
					</ul>
				</nav>    		
   		</div> <!-- /top-bar --> 
   		
   	</div> <!-- /row --> 		
   </header> <!-- /header -->

core/templates/home/includes/intro.html
<div id="particles-js"></div>
<section id="intro">   

   	<div class="intro-overlay"></div>	

   	<div class="intro-content">
   		<div class="row">

   			<div class="col-twelve">

	   			<h5>print('Hello, World')</h5>
	   			<h1>I'm Sahadev Bite</h1>

	   			<p class="intro-position">
               {% for skills in home_skills %}
	   				<span>{{ skills.name }}</span>
               {% endfor %}
	   			</p>

	   			<a class="button stroke smoothscroll" href="#about" title="">More About Me</a>

	   		</div>  
   			
   		</div>   		 		
   	</div> <!-- /intro-content --> 

   	<ul class="intro-social">        
      {% for list in social %}
         <li><a href="{{ list.url }}"><i class="fa fa-{{ list.name }}"></i></a></li>
      {% endfor %}
      </ul> <!-- /intro-social -->      	
</section> <!-- /intro -->

core/templates/home/includes/projects.html
{% load static %}
<section id="portfolio">

		<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>Projects and Creations</h5>
   			<h1>Check Out Some of My Works.</h1>

   			<p class="lead">All my works are all Open Sourced on <a href="https://github.com/sahadevbite">GitHub</a></p>

   		</div>   		
   	</div> <!-- /section-intro--> 
	<div class="row">
		<div id="projects-carousal" class="owl-carousel">
		
		{% for project in projects %}
			<div class="project-list">
				<div class="row">
					<div class="col-five tab-full">
						<img class="projectimg" src="{{project.image_url}}">
					</div>
					<div class="col-seven tab-full">
						<h1><a href="{{project.url}}">{{project.name}} <a href="{{project.github_url}}"><i class="fa fa-github"></i></a></h1>
						<p><strong>Technology Stack Used: </strong>{{project.tech}}</p>
						<p><strong>Description: </strong>{{project.description}}</p>
					</div>
				</div>
			</div>
		{% endfor %}

		</div>
	</div>

	</section> <!-- /portfolio --> 

core/templates/home/includes/quotes.html
<section id="services" class="quote">

		<div class="overlay"></div>

<!-- 		<div class="row section-intro">
<div class="col-twelve">
  		  		
  		  			<h5>My Favorite Quotations</h5>
  		  		
  		  		</div>  		
   	</div> /section-intro -->

   	<div class="row services-content">

   		<div id="owl-slider" class="owl-carousel services-list">
        {% for quote in quotes %}
	      	<div class="service">	         

	            <div class="service-content">

		            <blockquote>
                   <p>{{quote.text}}</p>
                   <cite>{{quote.citiation}}</cite>
                </blockquote>

             	</div> 	      

    			</div> <!-- /service -->
          
        {% endfor %}

	      </div> <!-- /services-list -->
   		
   	</div> <!-- /services-content -->
		
	</section> <!-- /services -->

core/templates/home/includes/resume.html
<section id="resume" class="grey-section">

		<div class="row section-intro">
   		<div class="col-twelve">

   			<h5>Resume</h5>
   			<h1>More of my credentials.</h1>

   			<p class="lead"></p>

   		</div>   		
   	</div> <!-- /section-intro--> 

	{% include 'home/includes/work.html' %}
   	
   	{% include 'home/includes/academic.html' %}
		
	</section> <!-- /features -->

core/templates/home/includes/work.html
   	<div class="row resume-timeline">

   		<div class="col-twelve resume-header">

   			<h2>Work Experience</h2>

   		</div> <!-- /resume-header -->

   		<div class="col-twelve">

   			<div class="timeline-wrap">
   			{% for work in work %}
					<div class="timeline-block">

	   				<div class="timeline-ico">
	   					<i class="fa fa-briefcase"></i>
	   				</div>

	   				<div class="timeline-header">
	   					<h3>{{ work.position }}</h3>
	   					<p>{{work.start_date}} - {{work.end_date}}</p>
	   				</div>

	   				<div class="timeline-content">
	   					<h4>{{work.organization}} <a href="{{work.certificate}}" title="View Certificate"><i class="fa fa-file-text-o" aria-hidden="true"></i></a></h4>
	   					<p>{{work.description}}</p>
	   				</div>

	   			</div> <!-- /timeline-block -->
	   		{% endfor %}

   			</div> <!-- /timeline-wrap -->   			

   		</div> <!-- /col-twelve -->
   		
   	</div> <!-- /resume-timeline -->